apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
  namespace: expense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend 
  template:
    metadata:
      labels:
        app: frontend
        project: expense
        environment: dev 
    spec:
      containers:
      - name: frontend
        image: arun596/frontend:1.0.0
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: expense

spec:
  type: LoadBalancer 
  selector: # labels are used as selectors
     app: frontend
     project: expense
     environment: dev 
  ports:
  - protocol: TCP
    port: 80    # service port
    targetPort: 8080 # target port in the pod
